name: Deploy to Hostinger

on:
  push:
    branches:
      - main # ganti dengan nama branch utama kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write deploy info
        shell: bash
        run: |
          echo "commit: $GITHUB_SHA" > deploy-info.txt
          echo "deployed_at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> deploy-info.txt

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # folder yang mau di-upload (./  = semua file)
          server-dir: /home/u838818830/domains/redlineacademy.com.au/public_html/ # folder tujuan di Hostinger
